version: "3.7"
services:
  app:
    build: .
    image: labcodevops/scraping_aml:0.0.1
    volumes:
      - .:/usr/local/Scraping_AML
    ports:
      - 3000:8000
    environment:
      - PYTHONPATH=/usr/local/Scraping_AML/api